konani_map:
    resource: "@KonaniMapBundle/Resources/config/routing.yml"
    prefix:   /

frontend:
    resource: "@FrontendBundle/Resources/config/routing.yml"
    prefix:   /

konani_cart:
    resource: "@KonaniCartBundle/Resources/config/routing.yml"
    prefix:   /

konani_video:
    resource: "@KonaniVideoBundle/Resources/config/routing.yml"
    prefix:   /video/

konani_admin:
    resource: "@KonaniAdminBundle/Resources/config/routing.yml"
    prefix:   /

konani_user:
    resource: "@KonaniUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

